name = "safeanesthesia-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[env.production]
workers_dev = true
vars = { ENVIRONMENT = "production", CONTACT_EMAIL = "info@spooapmafrica.com" }
